# Uncomment the next line to define a global platform for your project
platform :ios, '15'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'KGoogleMap', '0.1.0-beta.21'
  pod 'GoogleMaps'
end
